### ISSUE TITLE
Use DS4 controller instead of F710 logitech.

### ISSUE THREAD

**Issue by PallottaEnrico** [f1tenth/f1tenth_system#10]
Hi, i don't have a f710 logitech controller and i would like to use a dualshock 4.
Is there a way to do it? I didn't find any info about it on the documentation.

**Comment by hzheng40** [comment]
You can just put the DS4 in pairing mode, then in the Bluetooth settings on the Jetson, pair the joystick.
After it's paired, you can check the device id for the joystick, it's usually /dev/input/js0.
you can then change the line in https://github.com/f1tenth/f1tenth_system/blob/7b4fa8f225055a3b7bab80515a432773ff36dea7/f1tenth_stack/config/joy_teleop.yaml#L3 to ```device_id: 0``` if the id is js0.
