### ISSUE TITLE
Reverse SERVO direction

### ISSUE THREAD

**Issue by zlg9folira** [f1tenth/f1tenth_system#6]
I am trying to get joy_teleop working. What will fix it if servo (steering) direction is reversed (left steers to the right and right joy steers it to the left) ?. I am trying to find that point in the code where I can reverse the command. Any help is appreciated.

**Comment by hzheng40** [comment]
You can try to negate the scale on this line [here](https://github.com/f1tenth/f1tenth_system/blob/f1284b76cb4c3e9fe67a3cbf32ce86433bac6cf0/racecar/racecar/config/racecar-v2/joy_teleop.yaml#L37).

If that doesn't work, try to adjust the values on lines 16 and 17 [here](https://github.com/f1tenth/f1tenth_system/blob/f1284b76cb4c3e9fe67a3cbf32ce86433bac6cf0/racecar/racecar/config/racecar-v2/vesc.yaml#L15) to reverse the direction.

**Comment by zlg9folira** [comment]
Your first suggestion worked, thanks Billy . Launching `joy_teleop`, I can control the steering and motor for just a few seconds and after that non of joy control commands work. At the same time, I can see the following logs in terminal:
```
[vesc/low_level/ackermann_cmd_mux-10] process has finished cleanly
[vesc/high_level/ackermann_cmd_mux-8] process has finished cleanly
```
Inside log files:
```
[ INFO] [1***865.771510514]: Loading nodelet /vesc/low_level/ackermann_cmd_mux of type ackermann_cmd_mux/AckermannCmdMuxNodelet to manager ackermann_cmd_mux_nodelet_manager with the following remappings:
[ INFO] [1***890.524384706]: Bond broken, exiting
```
Node remains running without further error. There is just lack of control very soon after launching the node. Should I open a new issue for this ?

**Comment by hzheng40** [comment]
Are there any other error messages?
Can you provide your exact VESC hardware and firmware version, and any modifications you made to the packages?

**Comment by zlg9folira** [comment]
There is no any other error. I am using VESC hw 4.2 and fw 1.8. The VESC pkg I am using is the one provided by [MIT](https://github.com/mit-racecar/vesc) team and is compatible with hw 4.2. The only change I made to the package is that the joystick  (`joy`) is connected to and runs on different machine. So, `joy_teleop` node on the car subscribes to `/joy` over network. I cannot see any network delay here, car receives `joy` commands almost in real-time.

**Comment by hzheng40** [comment]
Ok, your setup is uncharted territory for us so unfortunately, I might not be very helpful.
From some searching online it sounds like it could be a system time issue between the remote and the car. The command mux nodelet might be throwing errors because the stamped time from the joy messages is ahead of the system time on the car.
Other than that I have no idea what the error could be.
